//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4927.
// 
namespace Entretien.Client.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    using Microsoft.Synchronization.Data;
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEntretienSyncContract", Namespace="http://tempuri.org/")]
    public partial class EntretienSyncService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EntretienSyncService() {
            this.Url = "http://192.168.0.81:8080/EntretienSyncService/";
        }
        
        /// <remarks/>
        
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncGroupMetadata {
        
        private string groupNameField;
        
        private SyncAnchor newAnchorField;
        
        private SyncAnchor maxAnchorField;
        
        private int batchCountField;
        
        private SyncTableMetadata[] tablesMetadataField;
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor NewAnchor {
            get {
                return this.newAnchorField;
            }
            set {
                this.newAnchorField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor MaxAnchor {
            get {
                return this.maxAnchorField;
            }
            set {
                this.maxAnchorField = value;
            }
        }
        
        /// <remarks/>
        public int BatchCount {
            get {
                return this.batchCountField;
            }
            set {
                this.batchCountField = value;
            }
        }
        
        /// <remarks/>
        public SyncTableMetadata[] TablesMetadata {
            get {
                return this.tablesMetadataField;
            }
            set {
                this.tablesMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncAnchor {
        
        private byte[] anchorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Anchor {
            get {
                return this.anchorField;
            }
            set {
                this.anchorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncTableInfo {
        
        private string tableNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncServerInfo {
        
        private SyncTableInfo[] tablesInfoField;
        
        /// <remarks/>
        public SyncTableInfo[] TablesInfo {
            get {
                return this.tablesInfoField;
            }
            set {
                this.tablesInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncSchema {
        
        private System.Data.DataSet schemaDataSetField;
        
        /// <remarks/>
        public System.Data.DataSet SchemaDataSet {
            get {
                return this.schemaDataSetField;
            }
            set {
                this.schemaDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncConflict {
        
        private ConflictType conflictTypeField;
        
        private string errorMessageField;
        
        private SyncStage syncStageField;
        
        private System.Data.DataTable serverChangeField;
        
        private System.Data.DataTable clientChangeField;
        
        /// <remarks/>
        public ConflictType ConflictType {
            get {
                return this.conflictTypeField;
            }
            set {
                this.conflictTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public SyncStage SyncStage {
            get {
                return this.syncStageField;
            }
            set {
                this.syncStageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable ServerChange {
            get {
                return this.serverChangeField;
            }
            set {
                this.serverChangeField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable ClientChange {
            get {
                return this.clientChangeField;
            }
            set {
                this.clientChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ConflictType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        ErrorsOccurred,
        
        /// <remarks/>
        ClientUpdateServerUpdate,
        
        /// <remarks/>
        ClientUpdateServerDelete,
        
        /// <remarks/>
        ClientDeleteServerUpdate,
        
        /// <remarks/>
        ClientInsertServerInsert,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SyncStage {
        
        /// <remarks/>
        ReadingSchema,
        
        /// <remarks/>
        CreatingSchema,
        
        /// <remarks/>
        ReadingMetadata,
        
        /// <remarks/>
        CreatingMetadata,
        
        /// <remarks/>
        DeletingMetadata,
        
        /// <remarks/>
        WritingMetadata,
        
        /// <remarks/>
        UploadingChanges,
        
        /// <remarks/>
        DownloadingChanges,
        
        /// <remarks/>
        ApplyingInserts,
        
        /// <remarks/>
        ApplyingUpdates,
        
        /// <remarks/>
        ApplyingDeletes,
        
        /// <remarks/>
        GettingInserts,
        
        /// <remarks/>
        GettingUpdates,
        
        /// <remarks/>
        GettingDeletes,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncTableProgress {
        
        private string tableNameField;
        
        private int insertsField;
        
        private int updatesField;
        
        private int deletesField;
        
        private int changesAppliedField;
        
        private int changesFailedField;
        
        private SyncConflict[] conflictsField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public int Inserts {
            get {
                return this.insertsField;
            }
            set {
                this.insertsField = value;
            }
        }
        
        /// <remarks/>
        public int Updates {
            get {
                return this.updatesField;
            }
            set {
                this.updatesField = value;
            }
        }
        
        /// <remarks/>
        public int Deletes {
            get {
                return this.deletesField;
            }
            set {
                this.deletesField = value;
            }
        }
        
        /// <remarks/>
        public int ChangesApplied {
            get {
                return this.changesAppliedField;
            }
            set {
                this.changesAppliedField = value;
            }
        }
        
        /// <remarks/>
        public int ChangesFailed {
            get {
                return this.changesFailedField;
            }
            set {
                this.changesFailedField = value;
            }
        }
        
        /// <remarks/>
        public SyncConflict[] Conflicts {
            get {
                return this.conflictsField;
            }
            set {
                this.conflictsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncGroupProgress {
        
        private string groupNameField;
        
        private SyncTableProgress[] tablesProgressField;
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public SyncTableProgress[] TablesProgress {
            get {
                return this.tablesProgressField;
            }
            set {
                this.tablesProgressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncContext {
        
        private SyncGroupProgress groupProgressField;
        
        private int originatorIdField;
        
        private SyncAnchor newAnchorField;
        
        private SyncAnchor maxAnchorField;
        
        private int batchCountField;
        
        private System.Data.DataSet dataSetField;
        
        /// <remarks/>
        public SyncGroupProgress GroupProgress {
            get {
                return this.groupProgressField;
            }
            set {
                this.groupProgressField = value;
            }
        }
        
        /// <remarks/>
        public int OriginatorId {
            get {
                return this.originatorIdField;
            }
            set {
                this.originatorIdField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor NewAnchor {
            get {
                return this.newAnchorField;
            }
            set {
                this.newAnchorField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor MaxAnchor {
            get {
                return this.maxAnchorField;
            }
            set {
                this.maxAnchorField = value;
            }
        }
        
        /// <remarks/>
        public int BatchCount {
            get {
                return this.batchCountField;
            }
            set {
                this.batchCountField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncParameter {
        
        private string nameField;
        
        private object valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncSession {
        
        private int originatorIdField;
        
        private System.Guid clientIdField;
        
        private SyncParameter[] customParametersField;
        
        /// <remarks/>
        public int OriginatorId {
            get {
                return this.originatorIdField;
            }
            set {
                this.originatorIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomParameters")]
        public SyncParameter[] CustomParameters {
            get {
                return this.customParametersField;
            }
            set {
                this.customParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncTableMetadata {
        
        private string tableNameField;
        
        private SyncDirection syncDirectionField;
        
        private SyncAnchor lastSentAnchorField;
        
        private SyncAnchor lastReceivedAnchorField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public SyncDirection SyncDirection {
            get {
                return this.syncDirectionField;
            }
            set {
                this.syncDirectionField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor LastSentAnchor {
            get {
                return this.lastSentAnchorField;
            }
            set {
                this.lastSentAnchorField = value;
            }
        }
        
        /// <remarks/>
        public SyncAnchor LastReceivedAnchor {
            get {
                return this.lastReceivedAnchorField;
            }
            set {
                this.lastReceivedAnchorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SyncDirection {
        
        /// <remarks/>
        DownloadOnly,
        
        /// <remarks/>
        UploadOnly,
        
        /// <remarks/>
        Bidirectional,
        
        /// <remarks/>
        Snapshot,
    }
}
